name: cr_json_widget
description: A widget, that visualises a tree structure, where a node can be any widget.
version: 1.1.1
homepage: https://github.com/Cleveroad/cr_json_widget

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
